import {
  User,
  Incident,
  IncidentStats,
  KpiSummary,
  Machine,
  AlertRule,
  DataQualityReport,
  QuarantineRecord,
  AuditLog
} from '../types';

export const mockUsers: User[] = [
  { user_id: 'usr_admin_01', username: 'admin', email: 'admin@factorypulse.io', full_name: 'System Administrator', role: 'ADMIN', is_active: true },
  { user_id: 'usr_eng_01', username: 'engineer', email: 'engineer@factorypulse.io', full_name: 'Lead Reliability Engineer', role: 'ENGINEER', is_active: true },
  { user_id: 'usr_sup_01', username: 'supervisor', email: 'supervisor@factorypulse.io', full_name: 'Shift Supervisor (Alpha)', role: 'SUPERVISOR', is_active: true },
  { user_id: 'usr_op_01', username: 'operator', email: 'operator@factorypulse.io', full_name: 'CNC Station Operator', role: 'OPERATOR', is_active: true },
];

export const mockKpis: KpiSummary = {
  oee: 76.8,
  availability: 86.4,
  performance: 91.2,
  quality: 97.5,
  total_production: 300000,
  good_units: 292500,
  scrap_units: 7500,
  rejection_rate_pct: 2.5,
  total_downtime_minutes: 2450.0,
  active_machines_count: 24,
  open_incidents_count: 5,
};

export const mockMachines: Machine[] = [
  {
    machine_id: 'MCH-DET-01',
    machine_name: '5-Axis CNC Milling Center 01',
    machine_type: 'CNC_MILLING',
    ideal_cycle_time_sec: 45.0,
    is_bottleneck: true,
    line_id: 'LINE-ENG-01',
    line_name: 'Engine Block Machining Line',
    factory_id: 'FAC-DET-01',
    factory_name: 'Detroit Propulsion Plant',
    current_vibration_rms: 4.85,
    current_temperature_c: 84.2,
    current_pressure_bar: 5.8,
    has_anomaly: true,
    machine_status: 'WARNING',
  },
  {
    machine_id: 'MCH-DET-02',
    machine_name: 'Robotic Laser Weld Cell 02',
    machine_type: 'ROBOTIC_WELDING',
    ideal_cycle_time_sec: 30.0,
    is_bottleneck: false,
    line_id: 'LINE-BOD-02',
    line_name: 'Body-in-White Framing Line',
    factory_id: 'FAC-DET-01',
    factory_name: 'Detroit Propulsion Plant',
    current_vibration_rms: 1.82,
    current_temperature_c: 62.0,
    current_pressure_bar: 6.1,
    has_anomaly: false,
    machine_status: 'RUNNING',
  },
  {
    machine_id: 'MCH-STU-01',
    machine_name: 'High-Tonnage Stamping Press 01',
    machine_type: 'STAMPING_PRESS',
    ideal_cycle_time_sec: 12.0,
    is_bottleneck: true,
    line_id: 'LINE-STP-01',
    line_name: 'Chassis Stamping Line',
    factory_id: 'FAC-STU-02',
    factory_name: 'Stuttgart Precision Assembly',
    current_vibration_rms: 2.15,
    current_temperature_c: 71.4,
    current_pressure_bar: 5.9,
    has_anomaly: false,
    machine_status: 'RUNNING',
  },
  {
    machine_id: 'MCH-STU-02',
    machine_name: 'Precision Injection Molding 02',
    machine_type: 'INJECTION_MOLDING',
    ideal_cycle_time_sec: 60.0,
    is_bottleneck: false,
    line_id: 'LINE-STP-01',
    line_name: 'Chassis Stamping Line',
    factory_id: 'FAC-STU-02',
    factory_name: 'Stuttgart Precision Assembly',
    current_vibration_rms: 5.20,
    current_temperature_c: 96.8,
    current_pressure_bar: 4.2,
    has_anomaly: true,
    machine_status: 'DOWNTIME',
  },
  {
    machine_id: 'MCH-YOK-01',
    machine_name: 'Automated Battery Cell Assembly 01',
    machine_type: 'AUTOMATED_ASSEMBLY',
    ideal_cycle_time_sec: 25.0,
    is_bottleneck: false,
    line_id: 'LINE-BAT-01',
    line_name: 'Battery Pack Integration Line',
    factory_id: 'FAC-YOK-03',
    factory_name: 'Yokohama Electric Systems',
    current_vibration_rms: 1.45,
    current_temperature_c: 58.6,
    current_pressure_bar: 6.0,
    has_anomaly: false,
    machine_status: 'RUNNING',
  },
  {
    machine_id: 'MCH-YOK-02',
    machine_name: 'Electrostatic Paint Spray Robot 01',
    machine_type: 'PAINT_BOOTH',
    ideal_cycle_time_sec: 90.0,
    is_bottleneck: false,
    line_id: 'LINE-BAT-01',
    line_name: 'Battery Pack Integration Line',
    factory_id: 'FAC-YOK-03',
    factory_name: 'Yokohama Electric Systems',
    current_vibration_rms: 2.30,
    current_temperature_c: 66.2,
    current_pressure_bar: 6.2,
    has_anomaly: false,
    machine_status: 'RUNNING',
  }
];

export let mockIncidents: Incident[] = [
  {
    incident_id: 'INC-20260917-001',
    alert_id: 'ALT-9021',
    machine_id: 'MCH-DET-01',
    rule_name: 'Vibration RMS Threshold Exceeded',
    metric_name: 'vibration_rms',
    observed_value: 4.85,
    threshold_value: 4.50,
    severity: 'CRITICAL',
    status: 'OPEN',
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    incident_id: 'INC-20260917-002',
    alert_id: 'ALT-9022',
    machine_id: 'MCH-STU-02',
    rule_name: 'Thermal Runaway & Overheat',
    metric_name: 'temperature_c',
    observed_value: 96.80,
    threshold_value: 90.00,
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    assigned_to: 'usr_eng_01',
    assignee_name: 'Lead Reliability Engineer',
    acknowledged_at: new Date(Date.now() - 40 * 60000).toISOString(),
    acknowledged_by_name: 'Shift Supervisor (Alpha)',
    root_cause: 'Why 1: High spindle temp -> Why 2: Coolant flow restricted -> Why 3: Particulate clogged solenoid filter mesh.',
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    incident_id: 'INC-20260917-003',
    alert_id: 'ALT-9023',
    machine_id: 'MCH-DET-01',
    rule_name: 'Micro-Stoppage Surge Detected',
    metric_name: 'micro_stoppages_1hr',
    observed_value: 7.00,
    threshold_value: 5.00,
    severity: 'WARNING',
    status: 'ACKNOWLEDGED',
    acknowledged_at: new Date(Date.now() - 15 * 60000).toISOString(),
    acknowledged_by_name: 'CNC Station Operator',
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    incident_id: 'INC-20260917-004',
    alert_id: 'ALT-9024',
    machine_id: 'MCH-YOK-01',
    rule_name: 'Hydraulic Pressure Drop',
    metric_name: 'pressure_bar',
    observed_value: 4.80,
    threshold_value: 5.00,
    severity: 'WARNING',
    status: 'RESOLVED',
    assigned_to: 'usr_eng_01',
    assignee_name: 'Lead Reliability Engineer',
    acknowledged_at: new Date(Date.now() - 90 * 60000).toISOString(),
    acknowledged_by_name: 'Lead Reliability Engineer',
    root_cause: 'Pressure accumulator seal wear allowed nitrogen backleakage.',
    corrective_action: 'Replaced elastomeric bladder and recharged nitrogen reservoir to 6.2 bar.',
    resolved_at: new Date(Date.now() - 20 * 60000).toISOString(),
    resolved_by_name: 'Lead Reliability Engineer',
    resolution_notes: 'Verified stable 6.0 bar line pressure over 10 consecutive assembly cycles.',
    created_at: new Date(Date.now() - 110 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60000).toISOString(),
  },
];

export let mockRules: AlertRule[] = [
  {
    rule_id: 'RUL-001',
    rule_name: 'High Vibration RMS Threshold',
    metric_name: 'vibration_rms',
    comparison_operator: '>',
    threshold_value: 4.5,
    severity: 'CRITICAL',
    machine_type: 'ALL',
    is_active: true,
    description: 'Triggers when machine bearing vibration exceeds 4.5 mm/s RMS.',
  },
  {
    rule_id: 'RUL-002',
    rule_name: 'Spindle Temperature Thermal Alarm',
    metric_name: 'temperature_c',
    comparison_operator: '>',
    threshold_value: 85.0,
    severity: 'CRITICAL',
    machine_type: 'ALL',
    is_active: true,
    description: 'Triggers when spindle or motor temperature exceeds 85°C.',
  },
  {
    rule_id: 'RUL-003',
    rule_name: 'Hydraulic Low Pressure Alert',
    metric_name: 'pressure_bar',
    comparison_operator: '<',
    threshold_value: 5.2,
    severity: 'WARNING',
    machine_type: 'ALL',
    is_active: true,
    description: 'Warns when hydraulic fluid pressure drops below 5.2 bar.',
  },
  {
    rule_id: 'RUL-004',
    rule_name: 'Micro-Stoppage Surge Alarm',
    metric_name: 'micro_stoppages_1hr',
    comparison_operator: '>',
    threshold_value: 4.0,
    severity: 'WARNING',
    machine_type: 'ALL',
    is_active: true,
    description: 'Detects repetitive short stoppages (<5m) degrading line performance.',
  },
  {
    rule_id: 'RUL-005',
    rule_name: 'First-Pass Yield Quality Drop',
    metric_name: 'quality_rate',
    comparison_operator: '<',
    threshold_value: 95.0,
    severity: 'WARNING',
    machine_type: 'ALL',
    is_active: true,
    description: 'Triggers when shift quality rate falls below world-class 95% target.',
  },
];

export const mockDataQuality: DataQualityReport = {
  warehouse_summary: {
    total_records_stored: 509753,
    fact_production_rows: 300000,
    fact_sensor_telemetry_rows: 159757,
    fact_downtime_rows: 14998,
    fact_quality_rows: 34998,
    quarantine_rows: 600,
  },
  pipeline_health: {
    rows_extracted: 512100,
    rows_loaded: 509753,
    rows_deduplicated: 1747,
    rows_rejected: 600,
    data_validity_pct: 99.54,
    quarantine_rate_pct: 0.12,
  },
  telemetry_metrics: {
    total_sensor_readings: 159757,
    sensor_anomalies_detected: 1842,
    anomaly_rate_pct: 1.15,
  },
  operational_governance: {
    open_incidents_count: 5,
    resolved_incidents_count: 95,
    overall_data_health: 'EXCELLENT',
  },
};

export const mockQuarantine: QuarantineRecord[] = [
  {
    quarantine_id: 'QR-001',
    batch_identifier: 'BATCH-20260917-001',
    source_stream: 'production_stream',
    raw_record: { part_serial_number: 'SN-ERR-991', cycle_time_seconds: -12.4, machine_id: 'MCH-DET-01' },
    rejection_reason: 'Negative cycle_time_seconds (-12.4s) violates physical constraint',
    rejected_at: new Date(Date.now() - 120 * 60000).toISOString(),
  },
  {
    quarantine_id: 'QR-002',
    batch_identifier: 'BATCH-20260917-001',
    source_stream: 'sensor_telemetry',
    raw_record: { machine_id: 'MCH-STU-02', temperature_c: 450.0, vibration_rms: 25.0 },
    rejection_reason: 'Temperature 450°C exceeds sensor dynamic measurement range (>150°C)',
    rejected_at: new Date(Date.now() - 110 * 60000).toISOString(),
  },
  {
    quarantine_id: 'QR-003',
    batch_identifier: 'BATCH-20260917-001',
    source_stream: 'downtime_stream',
    raw_record: { machine_id: 'MCH-YOK-01', start_time: '2026-09-17 14:00:00', end_time: '2026-09-17 13:00:00' },
    rejection_reason: 'Downtime end_time is earlier than start_time',
    rejected_at: new Date(Date.now() - 95 * 60000).toISOString(),
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    job_id: 'JOB-901',
    pipeline_name: 'production_stream',
    batch_identifier: 'BATCH-20260917-001',
    start_time: new Date(Date.now() - 130 * 60000).toISOString(),
    end_time: new Date(Date.now() - 128 * 60000).toISOString(),
    rows_extracted: 302100,
    rows_loaded: 300000,
    rows_rejected: 600,
    rows_deduplicated: 1500,
    status: 'COMPLETED',
    execution_time_seconds: 134.9,
  },
  {
    job_id: 'JOB-902',
    pipeline_name: 'sensor_telemetry_stream',
    batch_identifier: 'BATCH-20260917-001',
    start_time: new Date(Date.now() - 127 * 60000).toISOString(),
    end_time: new Date(Date.now() - 126 * 60000).toISOString(),
    rows_extracted: 160000,
    rows_loaded: 159757,
    rows_rejected: 0,
    rows_deduplicated: 243,
    status: 'COMPLETED',
    execution_time_seconds: 31.8,
  },
];
