"""
FactoryPulse Manufacturing Simulator Configuration
Contains machine topologies, statistical distribution parameters, and generation limits.
"""

from datetime import datetime
from typing import Dict, List, Any

# Machine Fleet Specification
MACHINES: List[Dict[str, Any]] = [
    {
        "machine_id": "MCH-01-01",
        "line_id": "LINE-01-A",
        "factory_id": "FACT-01",
        "machine_name": "Schuler Servo Press 2500T",
        "machine_type": "HYDRAULIC_PRESS",
        "ideal_cycle_time_sec": 30.0,
        "base_temp_c": 62.0,
        "base_vib_rms": 2.1,
        "base_pressure_bar": 210.0,
        "base_power_kw": 180.0,
        "base_rpm": 950.0,
        "failure_prob_per_shift": 0.08,
        "scrap_prob": 0.015,
        "rework_prob": 0.025,
    },
    {
        "machine_id": "MCH-01-02",
        "line_id": "LINE-01-A",
        "factory_id": "FACT-01",
        "machine_name": "Aida Transfer Press 1000T",
        "machine_type": "HYDRAULIC_PRESS",
        "ideal_cycle_time_sec": 32.0,
        "base_temp_c": 58.0,
        "base_vib_rms": 1.8,
        "base_pressure_bar": 195.0,
        "base_power_kw": 120.0,
        "base_rpm": 880.0,
        "failure_prob_per_shift": 0.06,
        "scrap_prob": 0.012,
        "rework_prob": 0.020,
    },
    {
        "machine_id": "MCH-01-03",
        "line_id": "LINE-01-B",
        "factory_id": "FACT-01",
        "machine_name": "KUKA Robotic Cell Weld-01",
        "machine_type": "ROBOTIC_WELDER",
        "ideal_cycle_time_sec": 40.0,
        "base_temp_c": 52.0,
        "base_vib_rms": 1.4,
        "base_pressure_bar": 6.2,
        "base_power_kw": 35.0,
        "base_rpm": 1200.0,
        "failure_prob_per_shift": 0.05,
        "scrap_prob": 0.022,
        "rework_prob": 0.035,
    },
    {
        "machine_id": "MCH-01-04",
        "line_id": "LINE-01-B",
        "factory_id": "FACT-01",
        "machine_name": "Fanuc Spot Welding Cell 02",
        "machine_type": "ROBOTIC_WELDER",
        "ideal_cycle_time_sec": 40.0,
        "base_temp_c": 54.0,
        "base_vib_rms": 1.5,
        "base_pressure_bar": 6.5,
        "base_power_kw": 38.0,
        "base_rpm": 1200.0,
        "failure_prob_per_shift": 0.07,
        "scrap_prob": 0.025,
        "rework_prob": 0.040,
    },
    {
        "machine_id": "MCH-01-05",
        "line_id": "LINE-01-C",
        "factory_id": "FACT-01",
        "machine_name": "DMG MORI 5-Axis CNC Mill 01",
        "machine_type": "CNC_5AXIS",
        "ideal_cycle_time_sec": 60.0,
        "base_temp_c": 68.0,
        "base_vib_rms": 2.4,
        "base_pressure_bar": 70.0,
        "base_power_kw": 65.0,
        "base_rpm": 8500.0,
        "failure_prob_per_shift": 0.09,
        "scrap_prob": 0.018,
        "rework_prob": 0.030,
    },
    {
        "machine_id": "MCH-01-06",
        "line_id": "LINE-01-C",
        "factory_id": "FACT-01",
        "machine_name": "Mazak Integrex Multi-Tasking 02",
        "machine_type": "CNC_5AXIS",
        "ideal_cycle_time_sec": 55.0,
        "base_temp_c": 65.0,
        "base_vib_rms": 2.2,
        "base_pressure_bar": 68.0,
        "base_power_kw": 60.0,
        "base_rpm": 8000.0,
        "failure_prob_per_shift": 0.07,
        "scrap_prob": 0.016,
        "rework_prob": 0.025,
    },
    {
        "machine_id": "MCH-02-01",
        "line_id": "LINE-02-A",
        "factory_id": "FACT-02",
        "machine_name": "Atlas Copco Smart Assembly Cell",
        "machine_type": "CONVEYOR_SYSTEM",
        "ideal_cycle_time_sec": 45.0,
        "base_temp_c": 44.0,
        "base_vib_rms": 0.9,
        "base_pressure_bar": 5.8,
        "base_power_kw": 22.0,
        "base_rpm": 600.0,
        "failure_prob_per_shift": 0.04,
        "scrap_prob": 0.008,
        "rework_prob": 0.015,
    },
    {
        "machine_id": "MCH-02-02",
        "line_id": "LINE-02-A",
        "factory_id": "FACT-02",
        "machine_name": "Zeiss High-Speed CMM Inspector",
        "machine_type": "CMM_INSPECTION",
        "ideal_cycle_time_sec": 45.0,
        "base_temp_c": 21.0, # Climate controlled room
        "base_vib_rms": 0.3,
        "base_pressure_bar": 4.5,
        "base_power_kw": 12.0,
        "base_rpm": 0.0,
        "failure_prob_per_shift": 0.03,
        "scrap_prob": 0.005,
        "rework_prob": 0.010,
    },
    {
        "machine_id": "MCH-02-03",
        "line_id": "LINE-02-B",
        "factory_id": "FACT-02",
        "machine_name": "Hermle C42 5-Axis Machining Center",
        "machine_type": "CNC_5AXIS",
        "ideal_cycle_time_sec": 48.0,
        "base_temp_c": 64.0,
        "base_vib_rms": 2.1,
        "base_pressure_bar": 65.0,
        "base_power_kw": 55.0,
        "base_rpm": 9200.0,
        "failure_prob_per_shift": 0.06,
        "scrap_prob": 0.014,
        "rework_prob": 0.022,
    },
    {
        "machine_id": "MCH-03-01",
        "line_id": "LINE-03-A",
        "factory_id": "FACT-03",
        "machine_name": "Panasonic Battery Cell Welder",
        "machine_type": "ROBOTIC_WELDER",
        "ideal_cycle_time_sec": 42.0,
        "base_temp_c": 56.0,
        "base_vib_rms": 1.6,
        "base_pressure_bar": 6.8,
        "base_power_kw": 48.0,
        "base_rpm": 1100.0,
        "failure_prob_per_shift": 0.07,
        "scrap_prob": 0.028,
        "rework_prob": 0.045,
    },
    {
        "machine_id": "MCH-03-02",
        "line_id": "LINE-03-A",
        "factory_id": "FACT-03",
        "machine_name": "Bosch Rexroth Automated Line Conveyor",
        "machine_type": "CONVEYOR_SYSTEM",
        "ideal_cycle_time_sec": 42.0,
        "base_temp_c": 45.0,
        "base_vib_rms": 1.1,
        "base_pressure_bar": 5.5,
        "base_power_kw": 20.0,
        "base_rpm": 650.0,
        "failure_prob_per_shift": 0.03,
        "scrap_prob": 0.006,
        "rework_prob": 0.012,
    },
    {
        "machine_id": "MCH-03-03",
        "line_id": "LINE-03-B",
        "factory_id": "FACT-03",
        "machine_name": "Durr EcoPaint Automated Booth",
        "machine_type": "PAINT_BOOTH",
        "ideal_cycle_time_sec": 36.0,
        "base_temp_c": 50.0,
        "base_vib_rms": 1.7,
        "base_pressure_bar": 45.0,
        "base_power_kw": 140.0,
        "base_rpm": 2200.0,
        "failure_prob_per_shift": 0.08,
        "scrap_prob": 0.032,
        "rework_prob": 0.050,
    }
]

PRODUCTS = [
    {"product_id": "PROD-001", "name": "V8 Engine Block", "unit_cost": 1250.00, "scrap_cost": 420.00},
    {"product_id": "PROD-002", "name": "Turbocharger Housing", "unit_cost": 480.00, "scrap_cost": 160.00},
    {"product_id": "PROD-003", "name": "EV Battery Pack Enclosure", "unit_cost": 1850.00, "scrap_cost": 650.00},
    {"product_id": "PROD-004", "name": "Suspension Knuckle", "unit_cost": 320.00, "scrap_cost": 95.00},
    {"product_id": "PROD-005", "name": "Door Outer Panel", "unit_cost": 290.00, "scrap_cost": 85.00},
]

SHIFTS = [
    {"shift_id": "SHIFT-M", "start_hour": 6, "end_hour": 14},
    {"shift_id": "SHIFT-A", "start_hour": 14, "end_hour": 22},
    {"shift_id": "SHIFT-N", "start_hour": 22, "end_hour": 6},
]

DOWNTIME_REASONS = [
    {"reason_id": "DT-01", "is_planned": True, "weight": 0.15},
    {"reason_id": "DT-02", "is_planned": True, "weight": 0.15},
    {"reason_id": "DT-03", "is_planned": True, "weight": 0.10},
    {"reason_id": "DT-04", "is_planned": False, "weight": 0.12}, # Hydraulic Fail
    {"reason_id": "DT-05", "is_planned": False, "weight": 0.10}, # Spindle Overheat
    {"reason_id": "DT-06", "is_planned": False, "weight": 0.12}, # Tool Breakage
    {"reason_id": "DT-07", "is_planned": False, "weight": 0.08}, # Inverter Fault
    {"reason_id": "DT-08", "is_planned": False, "weight": 0.06}, # Sensor Drift
    {"reason_id": "DT-09", "is_planned": False, "weight": 0.05}, # Operator Wait
    {"reason_id": "DT-10", "is_planned": False, "weight": 0.04}, # Material Starve
    {"reason_id": "DT-11", "is_planned": False, "weight": 0.02}, # Downstream Block
    {"reason_id": "DT-12", "is_planned": False, "weight": 0.01}, # E-Stop
]

DEFECT_REASONS = [
    {"defect_id": "DEF-01", "weight": 0.30},
    {"defect_id": "DEF-02", "weight": 0.25},
    {"defect_id": "DEF-03", "weight": 0.15},
    {"defect_id": "DEF-04", "weight": 0.12},
    {"defect_id": "DEF-05", "weight": 0.08},
    {"defect_id": "DEF-06", "weight": 0.06},
    {"defect_id": "DEF-07", "weight": 0.04},
]
